"""'add'

Revision ID: 1ea74dd7e98c
Revises: cd6c89193358
Create Date: 2018-12-22 19:41:24.226164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea74dd7e98c'
down_revision = 'cd6c89193358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Powers', sa.Column('power_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Powers', 'power_name')
    # ### end Alembic commands ###
