"""'add'

Revision ID: 2fbe755d835b
Revises: faf26234a999
Create Date: 2019-01-02 11:10:17.896007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fbe755d835b'
down_revision = 'faf26234a999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ApprovalSov', 'user_truename',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ApprovalSov', 'user_truename',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=128),
               nullable=False)
    # ### end Alembic commands ###
