"""'add'

Revision ID: 5a4fc53b389b
Revises: 917e5ee31cda
Create Date: 2018-12-28 22:23:39.510391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a4fc53b389b'
down_revision = '917e5ee31cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ApprovalMould', 'mouldelement_name',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ApprovalMould', 'mouldelement_name',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               nullable=False)
    # ### end Alembic commands ###
