"""'add'

Revision ID: 7351f1197c81
Revises: df1bea286ac3
Create Date: 2018-12-27 03:39:29.579515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7351f1197c81'
down_revision = 'df1bea286ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApprovalMould', sa.Column('mouldelement_trans', sa.String(length=200), nullable=True))
    op.drop_column('ApprovalMould', 'mouldelement_icon_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApprovalMould', sa.Column('mouldelement_icon_id', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=False))
    op.drop_column('ApprovalMould', 'mouldelement_trans')
    # ### end Alembic commands ###
