"""'add'

Revision ID: 917e5ee31cda
Revises: 7351f1197c81
Create Date: 2018-12-27 03:41:56.115728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '917e5ee31cda'
down_revision = '7351f1197c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ApprovalMould', 'element_code')
    op.drop_column('ApprovalMould', 'mouldelement_trans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApprovalMould', sa.Column('mouldelement_trans', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True))
    op.add_column('ApprovalMould', sa.Column('element_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
