"""'add'

Revision ID: 9c709e6afcc0
Revises: 2fbe755d835b
Create Date: 2019-01-03 13:52:49.284184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c709e6afcc0'
down_revision = '2fbe755d835b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Elements',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('element_id', sa.String(length=64), nullable=False),
    sa.Column('element_name', sa.String(length=64), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=True),
    sa.Column('element_createtime', sa.DATETIME(), nullable=True),
    sa.Column('element_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_table('MouldElement',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('mouldelement_id', sa.String(length=64), nullable=False),
    sa.Column('mould_id', sa.String(length=64), nullable=False),
    sa.Column('element_id', sa.String(length=64), nullable=False),
    sa.Column('mouldelement_name', sa.Text(), nullable=True),
    sa.Column('mouldelement_icon_id', sa.String(length=200), nullable=True),
    sa.Column('mouldelement_index', sa.Integer(), nullable=True),
    sa.Column('mouldelement_rank', sa.String(length=200), nullable=True),
    sa.Column('mouldelement_status', sa.Integer(), nullable=True),
    sa.Column('mouldelement_createtime', sa.DATETIME(), nullable=True),
    sa.Column('mouldelement_updatetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('mouldelement_id')
    )
    op.create_table('Moulds',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('mould_id', sa.String(length=64), nullable=False),
    sa.Column('mould_name', sa.Text(), nullable=False),
    sa.Column('mould_time', sa.Integer(), nullable=True),
    sa.Column('mould_createtime', sa.DATETIME(), nullable=True),
    sa.Column('mould_updatetime', sa.DATETIME(), nullable=True),
    sa.Column('mould_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mould_id')
    )
    op.drop_table('moulds')
    op.drop_table('mould_element')
    op.drop_table('elements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('element_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('element_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('element_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('element_createtime', mysql.DATETIME(), nullable=True),
    sa.Column('element_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('element_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('mould_element',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('mouldelement_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('mould_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('element_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('mouldelement_name', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('mouldelement_icon_id', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True),
    sa.Column('mouldelement_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mouldelement_rank', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True),
    sa.Column('mouldelement_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mouldelement_createtime', mysql.DATETIME(), nullable=True),
    sa.Column('mouldelement_updatetime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('mouldelement_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('moulds',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('mould_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('mould_name', mysql.TEXT(collation='utf8_bin'), nullable=False),
    sa.Column('mould_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mould_createtime', mysql.DATETIME(), nullable=True),
    sa.Column('mould_updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('mould_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('mould_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Moulds')
    op.drop_table('MouldElement')
    op.drop_table('Elements')
    # ### end Alembic commands ###
