"""'add'

Revision ID: 9fb4bfde9a8e
Revises: 
Create Date: 2018-12-21 00:37:37.060949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb4bfde9a8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApprovalLevel',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('approvallevel_id', sa.String(length=64), nullable=False),
    sa.Column('approvallevel_status', sa.Integer(), nullable=True),
    sa.Column('approvallevel_index', sa.Integer(), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('approvallevel_id')
    )
    op.create_table('ApprovalMould',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('approvalmould_id', sa.String(length=64), nullable=False),
    sa.Column('element_name', sa.String(length=64), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=True),
    sa.Column('mouldelement_name', sa.Text(), nullable=False),
    sa.Column('mouldelement_icon_id', sa.String(length=200), nullable=False),
    sa.Column('mouldelement_index', sa.Integer(), nullable=True),
    sa.Column('element_value', sa.Text(), nullable=True),
    sa.Column('mouldelement_rank', sa.String(length=200), nullable=True),
    sa.Column('approvalsub_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('approvalmould_id')
    )
    op.create_table('ApprovalPower',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('approvalpower_id', sa.String(length=64), nullable=False),
    sa.Column('approvalpower_status', sa.Integer(), nullable=True),
    sa.Column('approvalpower_createtime', sa.DATETIME(), nullable=True),
    sa.Column('approvalpower_updatetime', sa.DATETIME(), nullable=True),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('approvalpower_id')
    )
    op.create_table('ApprovalSov',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('approvalsov_id', sa.String(length=64), nullable=False),
    sa.Column('approvalsov_suggestion', sa.Integer(), nullable=False),
    sa.Column('approvalsov_message', sa.Text(), nullable=True),
    sa.Column('approvalsov_createtime', sa.DATETIME(), nullable=True),
    sa.Column('user_truename', sa.String(length=128), nullable=False),
    sa.Column('approvalsub_id', sa.String(length=64), nullable=False),
    sa.Column('approvalsub_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('approvalsov_id')
    )
    op.create_table('ApprovalSub',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('approvalsub_id', sa.String(length=64), nullable=False),
    sa.Column('approval_name', sa.Text(), nullable=False),
    sa.Column('approvalsub_createtime', sa.DATETIME(), nullable=True),
    sa.Column('approvalsub_status', sa.Integer(), nullable=True),
    sa.Column('user_truename', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_telphone', sa.String(length=64), nullable=False),
    sa.Column('approvalsub_endtime', sa.DATETIME(), nullable=True),
    sa.Column('approvalsub_message', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('approvalsub_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('approvalsub_id')
    )
    op.create_table('Approvals',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('approval_name', sa.Text(), nullable=False),
    sa.Column('mould_id', sa.String(length=64), nullable=False),
    sa.Column('approval_status', sa.Integer(), nullable=True),
    sa.Column('approval_createtime', sa.DATETIME(), nullable=True),
    sa.Column('approval_updatetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_table('Notice',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('notice_id', sa.String(length=64), nullable=False),
    sa.Column('notice_title', sa.Text(), nullable=False),
    sa.Column('notice_message', sa.Text(), nullable=True),
    sa.Column('notice_createtime', sa.DATETIME(), nullable=True),
    sa.Column('notice_updatetime', sa.DATETIME(), nullable=True),
    sa.Column('notice_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('notice_id')
    )
    op.create_table('PowerTag',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('powertag_id', sa.String(length=64), nullable=False),
    sa.Column('power_id', sa.String(length=64), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('powertag_createtime', sa.DATETIME(), nullable=True),
    sa.Column('powertag_updatetime', sa.DATETIME(), nullable=True),
    sa.Column('powertag_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('powertag_id')
    )
    op.create_table('Powers',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('power_id', sa.String(length=64), nullable=False),
    sa.Column('power_name', sa.Text(), nullable=True),
    sa.Column('power_status', sa.Integer(), nullable=True),
    sa.Column('power_icon_id', sa.String(length=200), nullable=True),
    sa.Column('power_use_js', sa.String(length=200), nullable=True),
    sa.Column('power_createtime', sa.DATETIME(), nullable=True),
    sa.Column('power_updatetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('power_id')
    )
    op.create_table('Tags',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('tag_name', sa.String(length=256), nullable=False),
    sa.Column('tag_status', sa.Integer(), nullable=False),
    sa.Column('tag_level', sa.Integer(), nullable=True),
    sa.Column('tag_before_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('UserTags',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('usertag_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('usertag_createtime', sa.DATETIME(), nullable=True),
    sa.Column('usertag_updatetime', sa.DATETIME(), nullable=True),
    sa.Column('usertag_status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('usertag_id')
    )
    op.create_table('Users',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('user_password', sa.String(length=128), nullable=False),
    sa.Column('user_createtime', sa.DATETIME(), nullable=True),
    sa.Column('user_truename', sa.String(length=128), nullable=True),
    sa.Column('user_telphone', sa.String(length=20), nullable=True),
    sa.Column('user_email', sa.String(length=64), nullable=True),
    sa.Column('user_wechat', sa.String(length=64), nullable=True),
    sa.Column('user_qq', sa.String(length=64), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('user_status', sa.Integer(), nullable=False),
    sa.Column('user_location', sa.Text(), nullable=True),
    sa.Column('user_contract', sa.Text(), nullable=True),
    sa.Column('user_icon', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('elements',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('element_id', sa.String(length=64), nullable=False),
    sa.Column('element_name', sa.String(length=64), nullable=False),
    sa.Column('element_code', sa.Integer(), nullable=True),
    sa.Column('element_createtime', sa.DATETIME(), nullable=True),
    sa.Column('element_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_table('mould_element',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('mouldelement_id', sa.String(length=64), nullable=False),
    sa.Column('mould_id', sa.String(length=64), nullable=False),
    sa.Column('element_id', sa.String(length=64), nullable=False),
    sa.Column('mouldelement_name', sa.Text(), nullable=False),
    sa.Column('mouldelement_icon_id', sa.String(length=200), nullable=False),
    sa.Column('mouldelement_index', sa.Integer(), nullable=True),
    sa.Column('mouldelement_rank', sa.String(length=200), nullable=True),
    sa.Column('mouldelement_status', sa.Integer(), nullable=True),
    sa.Column('mouldelement_createtime', sa.DATETIME(), nullable=True),
    sa.Column('mouldelement_updatetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('mouldelement_id')
    )
    op.create_table('moulds',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('mould_id', sa.String(length=64), nullable=False),
    sa.Column('mould_name', sa.Text(), nullable=False),
    sa.Column('mould_time', sa.Integer(), nullable=True),
    sa.Column('mould_createtime', sa.DATETIME(), nullable=True),
    sa.Column('mould_updatetime', sa.DATETIME(), nullable=True),
    sa.Column('mould_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mould_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moulds')
    op.drop_table('mould_element')
    op.drop_table('elements')
    op.drop_table('Users')
    op.drop_table('UserTags')
    op.drop_table('Tags')
    op.drop_table('Powers')
    op.drop_table('PowerTag')
    op.drop_table('Notice')
    op.drop_table('Approvals')
    op.drop_table('ApprovalSub')
    op.drop_table('ApprovalSov')
    op.drop_table('ApprovalPower')
    op.drop_table('ApprovalMould')
    op.drop_table('ApprovalLevel')
    # ### end Alembic commands ###
