"""'add'

Revision ID: a07e18cdb1cf
Revises: 5a4fc53b389b
Create Date: 2019-01-02 10:06:12.411734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07e18cdb1cf'
down_revision = '5a4fc53b389b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApprovalMould', sa.Column('element_value_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ApprovalMould', 'element_value_name')
    # ### end Alembic commands ###
