"""'add'

Revision ID: b635f0e44104
Revises: cb4692bf158f
Create Date: 2019-01-09 03:08:27.470236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b635f0e44104'
down_revision = 'cb4692bf158f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductsQyt',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('sku_id', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('order_lock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.add_column('Tags', sa.Column('tag_sn', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tags', 'tag_sn')
    op.drop_table('ProductsQyt')
    # ### end Alembic commands ###
