"""'add'

Revision ID: c62cff6b2ba0
Revises: bbd0191b3694
Create Date: 2019-01-08 22:23:28.368620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62cff6b2ba0'
down_revision = 'bbd0191b3694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
