"""'add'

Revision ID: cb4692bf158f
Revises: c62cff6b2ba0
Create Date: 2019-01-08 22:51:11.041321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4692bf158f'
down_revision = 'c62cff6b2ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('sku_id', sa.String(length=200), nullable=False),
    sa.Column('i_id', sa.String(length=200), nullable=False),
    sa.Column('i_name', sa.Text(), nullable=False),
    sa.Column('properties_value', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sku_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Products')
    # ### end Alembic commands ###
