"""'add'

Revision ID: cd6c89193358
Revises: 9fb4bfde9a8e
Create Date: 2018-12-22 01:23:55.245574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd6c89193358'
down_revision = '9fb4bfde9a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PowersMeta', sa.Column('createtime', sa.DateTime(), nullable=True))
    op.add_column('PowersMeta', sa.Column('isdelete', sa.Boolean(), nullable=True))
    op.add_column('PowersMeta', sa.Column('updatetime', sa.DateTime(), nullable=True))
    op.alter_column('PowersMeta', 'power_id',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=False)
    op.alter_column('PowersMeta', 'powermeta_title',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=128),
               nullable=False)
    op.alter_column('Tags', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tags', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    op.alter_column('PowersMeta', 'powermeta_title',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=128),
               nullable=True)
    op.alter_column('PowersMeta', 'power_id',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    op.drop_column('PowersMeta', 'updatetime')
    op.drop_column('PowersMeta', 'isdelete')
    op.drop_column('PowersMeta', 'createtime')
    # ### end Alembic commands ###
