"""'add'

Revision ID: df1bea286ac3
Revises: 378050ad4d15
Create Date: 2018-12-26 16:18:32.044288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df1bea286ac3'
down_revision = '378050ad4d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mould_element', 'mouldelement_name',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mould_element', 'mouldelement_name',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               nullable=False)
    # ### end Alembic commands ###
