"""'add'

Revision ID: faf26234a999
Revises: a07e18cdb1cf
Create Date: 2019-01-02 11:01:45.578894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf26234a999'
down_revision = 'a07e18cdb1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApprovalSov', sa.Column('tag_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ApprovalSov', 'tag_id')
    # ### end Alembic commands ###
